apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-operator
  namespace: "argocd"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: "logging"
    server: https://kubernetes.default.svc
  sources:
  - chart: eck-operator
    repoURL: https://helm.elastic.co
    targetRevision: 2.14.0
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
